services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servidores-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://172.16.30.6:8095
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge